version: '3'

tasks:
  start:
    desc: Clean database and start fresh development server
    cmds:
      - task: clean
      - npm run start

  dev:
    desc: Start local development server
    cmds:
      - npm run start

  lint:
    desc: Run ESLint on TypeScript files
    cmds:
      - npm run lint

  test:
    desc: Run Jest tests
    cmds:
      - npm run test

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  check:
    desc: Run all pre-commit checks (lint, typecheck, test)
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  cli:
    desc: Run the CLI tool with arguments
    cmds:
      - npm run cli:run -- {{.CLI_ARGS}}

  cli:build:
    desc: Build the CLI tool
    cmds:
      - npm run cli:build

  cli:init:
    desc: Initialize a killall-tofu project in the current directory
    cmds:
      - npm run cli:run -- init {{.CLI_ARGS}}

  clean:
    desc: Clean the ~/.killall directory (removes database and all data)
    cmds:
      - node scripts/clean-database.js